title:         Feedbin Blog
description:   Rediscover RSS
domain:        http://blog.feedbin.com
email:         support@feedbin.com
permalink:     /:title/
highlighter:   true
paginate:      10
exclude:       [public, vendor, .bundle, log, Gemfile, Gemfile.lock, Capfile, config, lib]
search_index:  feedbin_help
search_server: http://localhost:9200
collections:
- topics